### ISSUE TITLE
eOS-6 ready?

### ISSUE THREAD

**Issue by dxps** [paysonwallach/gala-switch#2]
Hi Payson,

This looks awesome and very promising as you already noticed in [reddit post](https://www.reddit.com/r/elementaryos/comments/lt1qjc/i_got_tired_of_all_the_waiting_for_odin_posts_so/).

I tried on the current elementary OS daily build `20210319`, compile, build, and install is fine, however the behavior is wrong: look & feel is strange (it shows the thumbnail of the active window only) and it doesn't switch to any other window.

![image](https://user-images.githubusercontent.com/14140226/111838535-234b2800-8902-11eb-9589-9ea218b428eb.png)

Also, I've noticed that when there is no active window using it (pressing alt+tab) twice or so triggers a logout.

:question:  Any ideas/hints, please?

I'm quite new to eOS and I really want to contribute, so what I can share further on is the "configure" phase, maybe it helps:

```shell
meson --prefix=/usr --wipe build
The Meson build system
Version: 0.53.2
Source dir: /home/dxps/tmp/gala-switch
Build dir: /home/dxps/tmp/gala-switch/build
Build type: native build
Project name: switch
Project version: 0.1.0
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Vala compiler for the host machine: valac (valac 0.48.15)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency gala found: YES 3.3.2
Run-time dependency gee-0.8 found: YES 0.20.3
Run-time dependency gio-2.0 found: YES 2.64.6
Run-time dependency gio-unix-2.0 found: YES 2.64.6
Run-time dependency glib-2.0 found: YES 2.64.6
Run-time dependency gobject-2.0 found: YES 2.64.6
Run-time dependency granite found: YES 6.0.0
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency libmutter-2 found: NO (tried pkgconfig and cmake)
Run-time dependency libmutter-3 found: NO (tried pkgconfig and cmake)
Run-time dependency libmutter-4 found: NO (tried pkgconfig and cmake)
Run-time dependency libmutter-5 found: NO (tried pkgconfig and cmake)
Run-time dependency libmutter-6 found: YES 3.36.7
Dependency libmutter-6 found: YES 3.36.7 (cached)
Run-time dependency mutter-cogl-6 found: YES 3.36.7
Run-time dependency mutter-cogl-pango-6 found: YES 3.36.7
Run-time dependency mutter-cogl-path-6 found: YES 3.36.7
Run-time dependency mutter-clutter-6 found: YES 3.36.7
Run-time dependency libmutter-7 found: NO (tried pkgconfig and cmake)
Program meson/post_install.py found: YES (/usr/bin/python3 /home/dxps/tmp/gala-switch/meson/post_install.py)
Build targets in project: 1

Found ninja-1.10.0 at /usr/bin/ninja
```

Thanks!

**Comment by paysonwallach** [comment]
Hi Marius,

From the screenshot it does look odd... though the size of the indicator border is actually calculated from dimensions given by the window manager which are sometimes dramatically off. Was the window recently in full-screen? With regard to behaviour, by default the window switcher only cycles through the windows of the active application on the current workspace. This can be changed to cycle through all windows of the active application regardless of workspace by setting `org.pantheon.desktop.gala.plugins.switch.all-workspaces`. I would also recommend checking that the `switch-applications` and `switch-windows` commands under `org.gnome.desktop.wm.keybindings` are bound (I believe only one is by default). As to the crashes, that is an active issue that needs to be addressed.

What version of mutter is installed?

Thanks!

**Comment by kqvanity** [comment]
for me the fix for the problem was installing doconf-editor , and then substituting the default value of org.gnome.desktop.wm.keybindings.switch-applications with `['<Alt>Tab']`

**Comment by dxps** [comment]
@paysonwallach Really sorry for delayed feedback. Somehow I missed your answer. Thanks for the notes! Unfortunately, I switched to Pop!_OS for some months, so I cannot continue the investigation.
@z0xyz Thank you also for the hint!

**Comment by dxps** [comment]
If you all don't mind, I'll close the ticket and if anyone encounters the same issue and gets into it as part of the search results, then this would be at least a place to start.
