### ISSUE TITLE
Unable to switch between the multiple windows opened of the same application 

### ISSUE THREAD

**Issue by kqvanity** [paysonwallach/gala-switch#3]
If lets say i have two or three windows of chrome -or any other software- and wanted to switch between i would be able to only see chrome while alt tabbing rather than all of the instances / windows of chrome .

**Comment by paysonwallach** [comment]
If I understand correctly, I believe you will want to ensure that `org.gnome.desktop.wm.keybindings.switch-windows` is set (for example, to `['<Alt>Tab']`, to bind the action to `Alt+Tab`), as it does not have a default.
